import type { Metadata } from 'next';
import { DM_Sans } from 'next/font/google';
import '@xyflow/react/dist/style.css';
import './globals.css';

const dmSans = DM_Sans({
  subsets: ['latin'],
  display: 'swap',
});

export const metadata: Metadata = {
  title: 'Relicix ai ',
  description: 'Generated by create next app',
};

export default function RootLayout({
  children,
}: Readonly<{
  children: React.ReactNode;
}>) {
  return (
    <html lang="en" className="h-full antialiased">
      <body className={`${dmSans.className} flex min-h-full flex-col`}>
        {children}
      </body>
    </html>
  );
}
